version: '2'
services:
  api:
    image: finetune-api
    depends_on:
      - mongodb
    links:
      - mongodb:db
    ports:
      - 8000:8000
    container_name: api
    environment:
      - DOCKER=100

  client:
    image: finetune-client
    ports:
      - 9000:80
    depends_on:
      - api
    links:
      - api:api
    container_name: client
  
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - 27777:27017
    container_name: mongodb


 
